// /robots.txt — generated by Next.
// Disallow API and admin paths; rest is open.
export default function robots() {
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: ["/api/", "/admin/", "/_next/"],
      },
    ],
    sitemap: "https://iranobservatory.org/sitemap.xml",
    host: "https://iranobservatory.org",
  };
}
