// /robots.txt — generated by Next.
// Disallow API + admin paths; allow everything else.
// Sitemap absolute URL is required by Search Console.
export default function robots() {
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: ["/api/", "/admin/", "/_next/"],
      },
      // Major search bots — explicit allow for clarity
      { userAgent: "Googlebot", allow: "/" },
      { userAgent: "Bingbot", allow: "/" },
      // Block AI scrapers that don't drive traffic (optional — easy to remove)
      { userAgent: "GPTBot", disallow: "/" },
      { userAgent: "ClaudeBot", disallow: "/" },
      { userAgent: "CCBot", disallow: "/" },
    ],
    sitemap: "https://iranobservatory.org/sitemap.xml",
    host: "https://iranobservatory.org",
  };
}
